### ISSUE TITLE
Accuracy constant

### ISSUE THREAD

**Issue by srameshr** [dpa99c/cordova-plugin-request-location-accuracy#2] opened 2015-12-29 15:01 UTC
When the request accuracy is set to:

```
cordova.plugins.locationAccuracy.REQUEST_PRIORITY_NO_POWER
```

it fails to show the confirm dialog.

**Comment by dpa99c** [comment] 2016-01-03 09:02
Using this constant, the dialog will only be shown if Location is turned Off when the request is made. It will then show the dialog and selecting "OK" will turn Location On.
You can try this for yourself in the example project app: https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example

**Comment by dpa99c** [comment] 2016-01-03 09:02
Whoops, didn't mean to close it yet :-)

**Comment by srameshr** [comment] 2016-01-04 06:23
No I can confirm it otherwise. Whenever I have accuracy set to 

```
cordova.plugins.locationAccuracy.REQUEST_PRIORITY_NO_POWER
```

it fails to show the confirm dialog even though location is turned off!

**Comment by dpa99c** [comment] 2016-01-04 08:01
The plugin is passing the correct constant value to the Android API, however it may be that Android responds differently on different versions or platforms. This is not a bug with the plugin and there is nothing that can be done by this plugin to change that behaviour.

For example, on the Android 6.0 emulator, it works as I described - see [this screen capture video](http://ge.tt/api/1/files/3uJ1dCV2/0/blob?download) which illustrates the fact using the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example): the ["No Power"](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/www/index.html#L42) value is 0 which corresponds to [REQUEST_PRIORITY_NO_POWER ](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/blob/master/www/RequestLocationAccuracy.js#L13).

**Comment by srameshr** [comment] 2016-01-04 10:07
May be! I am not sure. It works with `low power` only for me on Nexus 5 and Moto E both running on Android 5.2.

Another thing I noticed is, whenever I include this plugin in any cordova app, some third party apps like `memory-booster` and `power-save` puts my cordova app in `red-zone` indicating that it consumes a lot of power and some apps mark it as `relatively wasteful`

**Comment by dpa99c** [comment] 2016-01-04 10:21
To be clear, this plugin is just a thin wrapper around the Google Play Services Location API. The plugin itself really doesn't do much except call this API (you can see yourself in the source code). Therefore, any third-party apps are likely to be looking for use of either Location Services or the Google Play Services Location API. As such, again there is nothing that can be done from within the plugin to prevent this. Therefore, I'm closing this issue on the basis that there's nothing practical that can be done from within the plugin to change these outcomes. I guess your choice is to either use it and live with the issues incurred by the Google Play Services API or don't use it.

**Closed as completed by dpa99c** 2016-01-04 10:21 UTC

**Comment by srameshr** [comment] 2016-01-04 10:22
Ok we are gonna use it and live with the issues! I was just noting what I saw not complaining.

**Comment by dpa99c** [comment] 2016-01-04 10:25
I understand - I wasn't shouting at you :-) Just pointing out that the plugin itself is really simple and therefore these issues arising from it using are due to the Google Play Services library rather than the plugin itself, meaning that we can't do much about them :-)
