### ISSUE TITLE
Plugin install error for Android build

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-request-location-accuracy#57] opened 2018-08-20 15:01 UTC
**I'm submitting a ...**  (check one with "x"):
- [ x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Install plugin and it generates this error:

```
C:\myapp\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\15.0.1\jars\classes.jar(com/google/android/gms/common/api/GoogleApiClient.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\myapp\platforms\android\src\org\apache\cordova\file\AssetFilesystem.java uses unchecked or unsafe operations
Note: Recompile with -Xlint:unchecked for details.
1 warning
```

> Due to many errors upgrading everything at once, I am rebuilding one plugin at a time, compiling the app to ensure no errors, and then moving on to the next plugin and repeating. This was plugin #30 that threw the first 'warning/error' - the app still compiled, but this was one of the errors I saw when upgrading everything at once (in fact, there were several of the play-services-base\15 (or 16, or 17) related to play services. This is also the first plugin, via this plugin by plugin install method (as of yet) to use any google/play-services.

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	`Version 7.0.1`
- Cordova platform version
	`android@6.3`
- Plugins & versions installed in project (including this plugin)
```
cl.rmd.cordova.dialoggps 0.0.2 "DialogGPS"
com.lampa.startapp 6.1.6 "startApp"
com.ludei.webview.plus 2.3.0 "Webview+"
com.peerio.cordova.plugin.carrier 1.0.1 "Carrier"
com.phonegap.plugins.nativesettingsopener 1.0.1 "Native settings"
com.vliesaputra.deviceinformation 1.0.1 "DeviceInformation"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-instagram-plugin 0.5.7 "Instagram"
cordova-plugin-admobpro 2.31.6 "AdMob Plugin Pro"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-device-motion 2.0.1 "Device Motion"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-fastrde-checkgps 1.0.0 "checkGPS"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-universal-clipboard 0.1.0 "Clipboard"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
- Dev machine OS and version, e.g.
    -  Windows 7 - 64bit SP1
        
_Android build issue:_	
- Node 6.10.3
- Target Android SDK version
	- targetSDK: 26

```
Cordova CLI: 7.0.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.3.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v6.10.3

```
As mentioned above, my app and its components are older - and I routinely have compatibility issues when upgrading to the latest and greatest.  So i tend to run my production app on the minimum requirements - thus my environment is running older versions of many things.

I am doing this upgrade now because of googles notices that apps minimum need to support SDK 26.  So I was upgrading from android@6.2.3 to @6.3 (probably give me about 6 more months before I am forced to upgrade to @7+)

**Comment by rolinger** [comment] 2018-08-20 15:05
On a side note, after the initial build that produced the above warning/error, I compile again and it does not happen.  Only on the install. 

Update: this is incorrect.  Install plugin, get warning/error on build.  build again, no error.  add next plugin (cordova-plugin-screensize) and build again and the warning comes back.

**Comment by dpa99c** [comment] 2018-08-20 15:10
That seems to be an build warning as opposed to a build error which leads to a build failure.

The example project seems to build OK with `cordova-android@6.3` in my dev environment without that warning:

<details>
<summary>console output</summary>

```

$ cordova -v
8.0.0

$ git clone https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example
Cloning into 'cordova-plugin-request-location-accuracy-example'...
remote: Counting objects: 95, done.
remote: Total 95 (delta 0), reused 0 (delta 0), pack-reused 95
Unpacking objects: 100% (95/95), done.

$ cd cordova-plugin-request-location-accuracy-example/
/cordova-plugin-request-location-accuracy-example

$ cordova platform add android@6.3
Using cordova-fetch for cordova-android@6.3
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: uk.co.workingedge.phonegap.plugins.example.requestlocationaccuracy
        Name: Request_Location_Accuracy_example
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-request-location-accuracy" in config.xml. Adding it to the project
Installing "cordova-plugin-request-location-accuracy" for android
Subproject Path: CordovaLib
Adding cordova-plugin-request-location-accuracy to package.json
Saved plugin info for "cordova-plugin-request-location-accuracy" to config.xml
Discovered plugin "cordova.plugins.diagnostic" in config.xml. Adding it to the project
Installing "cordova.plugins.diagnostic" for android
Subproject Path: CordovaLib
Adding cordova.plugins.diagnostic to package.json
Saved plugin info for "cordova.plugins.diagnostic" to config.xml
--save flag or autosave detected
Saving android@~6.3.0 into config.xml file ...
/cordova-plugin-request-location-accuracy-example

$ cordova plugin ls
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
/cordova-plugin-request-location-accuracy-example

$ cordova build android
ANDROID_HOME=G:\Users\dpa99\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_161
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_9fr7v5q7757g5nj3mlym8fewf.run(D:\Temp\cordova-plugin-request-location-accuracy-example\platforms\android\build.gradle:141)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk NO-SOURCE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint NO-SOURCE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript NO-SOURCE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk NO-SOURCE
:CordovaLib:copyReleaseLint NO-SOURCE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript NO-SOURCE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes NO-SOURCE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidArchLifecycleRuntime100Library
:prepareComAndroidSupportAnimatedVectorDrawable2610Library
:prepareComAndroidSupportAppcompatV72610Library
:prepareComAndroidSupportSupportCompat2610Library
:prepareComAndroidSupportSupportCoreUi2610Library
:prepareComAndroidSupportSupportCoreUtils2610Library
:prepareComAndroidSupportSupportFragment2610Library
:prepareComAndroidSupportSupportMediaCompat2610Library
:prepareComAndroidSupportSupportV42610Library
:prepareComAndroidSupportSupportVectorDrawable2610Library
:prepareComGoogleAndroidGmsPlayServicesBase1501Library
:prepareComGoogleAndroidGmsPlayServicesBasement1501Library
:prepareComGoogleAndroidGmsPlayServicesLocation1501Library
:prepareComGoogleAndroidGmsPlayServicesPlacesPlacereport1501Library
:prepareComGoogleAndroidGmsPlayServicesTasks1501Library
:prepareOrgApacheCordovaCordovaLib630DebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Temp\cordova-plugin-request-location-accuracy-example\platforms\android\src\cordova\plugins\Diagnostic.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugNdk NO-SOURCE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithDexForDebug
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:transformNative_libsWithStripDebugSymbolForDebug
:processDebugJavaRes NO-SOURCE
:transformResourcesWithMergeJavaResForDebug
:validateSigningDebug
:packageDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 43.917 secs
Built the following apk(s):
        D:/Temp/cordova-plugin-request-location-accuracy-example/platforms/android/build/outputs/apk/android-debug.apk
/cordova-plugin-request-location-accuracy-example
$

```

</details>

<br/>
I'd recommend ensuring all your Android SDK library components are up-to-date.

You can also check `platforms/android/build.gradle` to ensure no other plugins are pulling in a different version of Play Services library components. In the example project build above, I have these entries:

	compile "com.google.android.gms:play-services-location:15.+"
    compile "com.android.support:support-v4:26.+"
    compile "com.android.support:appcompat-v7:26.+"

You can use [cordova-android-support-gradle-release](https://github.com/dpa99c/cordova-android-support-gradle-release) and [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release) to override the versions of the Android Support Library and Play Services Library specified by installing plugins.

**Comment by rolinger** [comment] 2018-08-20 15:16
What is the difference between the two `gradle-release` plugins?  I have been using the `support` one and only over the last few days became aware of the `play-services` one.

My build.gradle file contains:
```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v4:26.+"
    compile "com.google.android.gms:play-services-ads:+"
    compile "com.google.android.gms:play-services-location:15.+"
    // SUB-PROJECT DEPENDENCIES END
}
```

**Comment by rolinger** [comment] 2018-08-20 15:18
Oh...do I need both `gradle-release` and should they be installed before other plugins - or after?  Often I find it does make a difference.

**Comment by dpa99c** [comment] 2018-08-20 15:22
`cordova-android-support-gradle-release` overrides the Android Support Library (`com.android.support`) and `cordova-android-play-services-gradle-release` overrides the Play Services Library (`com.google.android.gms`).

From your `build.gradle`, it looks like there's a version conflict so you'll need to use `cordova-android-play-services-gradle-release` to resolve it:

    cordova plugin add cordova-android-play-services-gradle-release  --variable PLAY_SERVICES_VERSION=15.+

Doesn't matter if you install it before or after other plugins since it will override their Gradle config during the Android build process.

**Comment by rolinger** [comment] 2018-08-20 15:37
cool.  Thanks.  I had not used the `play-services` one before which explains this issue.  I will report back in a bit.

**Comment by rolinger** [comment] 2018-08-20 15:49
I added:
```
`cordova plugin add cordova-android-play-services-gradle-release  --variable PLAY_SERVICES_VERSION=15.+`   (ver 1.4.3)
`cordova plugin add cordova-android-support-gradle-release` (ver 1.4.4)
```


And I am still getting the warning.  My build.gradle file still looks the same:
```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v4:26.+"
    compile "com.google.android.gms:play-services-ads:+"
    compile "com.google.android.gms:play-services-location:15.+"
    // SUB-PROJECT DEPENDENCIES END
}

```

**Comment by dpa99c** [comment] 2018-08-20 15:54
The `build.gradle` will remain unchanged - the plugin works by overriding the specified versions at build time while Gradle is running. The version mismatch is probably not the cause of your warning - I'd ignore that if it's not causing your build to fail.

**Comment by rolinger** [comment] 2018-08-20 16:19
Ok...thanks.  Lastly:

When compiling now, I notice this message being displayed:
```
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
```

However, I know that android@6.3 provides support for SDK 26.   Will this cause any problems?  I do have Android Studio (2.3.3) SDK Manager installed with SDKs 26, 27 and 28 installed.

Admittedly, I often get confused on the various compatibility issues....so I appreciate the extra help you have provided.

**Comment by dpa99c** [comment] 2018-08-21 08:14
The Android build process is a dark art these days.

SDK 26 should be fine with Support Library 27, but if you want to align them:

    cordova plugin rm cordova-android-support-gradle-release && cordova plugin add cordova-android-support-gradle-release --variable ANDROID_SUPPORT_VERSION=26.+

**Comment by rolinger** [comment] 2018-08-21 12:21
On a separate computer I decided to upgrade most everything and am having success with the usual suspects but am having problems with plugins that have never given problems before.  Go figure.

Cordova CLI: 8.0
Cordova-Android@7.1.1

All the google/android/play-service related plugins are installing fine which stunned me - in fact, so far I have not had to add any of the `gradle-release` SDK alignment plugins - but now its the old plugins that are causing errors because I think the new Cordova stuff is missing \platforms\android\AndriodManifst.xml file and \platforms\android\res\xml and \platforms\android\res\values folders and files.

**Comment by dpa99c** [comment] 2018-08-21 12:41
Yes the native Android project directory structure has changed in `cordova-android@7` in line with Android Studio v3, so plugins which explicitly reference filepaths such as `AndroidManifest.xml` will not work.

**Comment by rolinger** [comment] 2018-08-21 12:46
Is it simply just changing filepaths (and files) for the various plugins - or adding them back in - or does it tend to be much more invasive than that?  I still need these plugins.  This is so aggravating.

**Comment by dpa99c** [comment] 2018-08-21 12:52
Main difference is that the generated app files for `cordova-android@7` reside in `platforms/android/app/` whereas for `cordova-android@6` they reside in `platforms/android/`.

So `platforms/android/AndroidManifest.xml` => `platforms/android/app/AndroidManifest.xml`

You can update any plugins which make explicit references to use the new filepaths.

In my own plugins, where explicit references are made, I've made the hook scripts detect the `cordova-android` version and use the paths appropriate to the current version, for example [this script](https://github.com/dpa99c/cordova-android-support-gradle-release/blob/master/scripts/apply-changes.js).

**Comment by rolinger** [comment] 2018-08-21 12:55
Thanks, I will see if I can fork the various plugins and get these paths corrected.

I HOPE that is the only issue.

**Comment by rolinger** [comment] 2018-08-21 15:15
Interesting, just occurred to me that the script you referenced in your last comment could be the very thing that allowed me to install all the old plugins in a test environment with Cordova@8.0.0, Cordova-Android@7.1.0 and Ionic@3.18 - it all installed just fine.  But after the project start, the very first plugin I installed was `cordova-android-support-gradle-release`.  I did this months ago and everything installed just fine.  The problem though is that my app is in Ionic v1 and I need to convert everything to Ionic v3 which I haven't made much progress with.

So as I am upgrading everything now to work with Ionic v1 none of the older plugins were installing due to the app file paths (mentioned above).  So I was trying to trying to figure out how months ago the old plugins installed without issue and why they are breaking today - it turns out your `gradle-release` includes the script to correct old paths.  

The new install, that is breaking on the old plugins, however did not need the `gradle-release` to install and compile correctly.  When you posted the example script it dawned on me why the old plugins installed just fine months ago (cause I used the `gradle-release` then) and why they weren't installing now (cause I didn't need the `gradel-release` now).

I wonder if you can isolate that script and supply it as `cordova-android-v6-tov7-path-alignment` stand alone script for general use.  I bet you LOTS of ppl would find use for it.

**Comment by rolinger** [comment] 2018-08-21 16:07
I just tested the above theory and that's what it is.  Though apparently I don't need `cordova-android-support-gradle-release` for all the plugins that use firebase/play-service/etc, I do need to install it for all the legacy plugins for that one script that does the path alignment for plugins that have not been updated for cordova-android@7.x+

It fixed all of the old plugins except for this one:  `cordova-dialog-gps`  (related to \platforms\android\res\xml & ..\res\values)

Any chance you could split your alignment script out as a standalone?  Maybe add in some code that force checks plugins that need path alignment - even if there is no code to do the auto-alignment, at least have something that outputs "Plugin uses old path, fork plugin and add new path...".

Thoughts?

**Comment by rolinger** [comment] 2018-08-22 12:43
Wow...I did it.  Installed 41 plugins using Cordova@8.0.0 (upgraded from 7.0.1), Cordova-android@7.1.1 (upgraded from 6.2.3) and Ionic@1.3.4 (now just commonly known as Ionic v1).  Compiled and ran it....and ran it on an older Android phone running 5.1.1 - and it all works.  I am stunned.  just need to get that `cordova-dialog-gps` plugin working.  I will hard code all the plugin versions for maintenance releases for the production app....and this should give me plenty of time to finally migrate all my code to the latest Ionic v3 (or now even v4).   Huge...HUGE...sigh of relief.  

PS: Sorry to blow up your plugin "issue" with this thread...I had to cry on some ones shoulder.  ;)

**Comment by dpa99c** [comment] 2018-08-22 12:48
✋ good work. Worth the effort as it now makes adopting new plugin versions that much easier.
Closing this issue in celebration 🎉

**Closed as completed by dpa99c** 2018-08-22 12:48 UTC

**Comment by rolinger** [comment] 2018-08-22 14:10
I was trying to private msg you but couldn't see a way to do it.  So I posted here again.  Sorry about that.

I forked the cordova-dialog-gps plugin and need to modify the target paths for the plugin install, these paths don't exist nor can I seem to find where they have moved to.  Would you mind reviewing my changes below, I thought I had it, the forked plugin installed but when I compiled and ran it on my test phone I got the following errors:

`Alert: Error initializing Cordova: class not found` 
then
`Application Error: The connection to the server was unsuccessful (file:///android_asset/www/index.html)`

Orig:
```
    <platform name="android">
        <config-file target="res/xml/config.xml" parent="/*">  <!-- target path updated -->
            <feature name="DialogGPS">
                <param name="android-package" value="cl.rmd.cordova.dialoggps.DialogGPS"/>
            </feature>
        </config-file>
 
        <source-file src="src/android/DialogGPS.java" target-dir="src/cl/rmd/cordova/dialoggps" />
        <source-file src="www/icon/drawable-hdpi/ic_location.png"  target-dir="res/drawable-hdpi/"/> <!--  target paths updated -->
        <source-file src="www/icon/drawable-mdpi/ic_location.png"  target-dir="res/drawable-mdpi/"/>
        <source-file src="www/icon/drawable-xhdpi/ic_location.png"  target-dir="res/drawable-xhdpi/"/>
        <source-file src="www/icon/drawable-xxhdpi/ic_location.png"  target-dir="res/drawable-xxhdpi/"/>
        <source-file src="www/icon/drawable-xxxhdpi/ic_location.png"  target-dir="res/drawable-xxxhdpi/"/>

        <config-file target="AndroidManifest.xml"    parent="/manifest">
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
        </config-file>
```
Changed to:
```
    <platform name="android">
        <config-file target="app/src/main/res/xml/config.xml" parent="/*">  <!-- target path updated -->
            <feature name="DialogGPS">
                <param name="android-package" value="cl.rmd.cordova.dialoggps.DialogGPS"/>
            </feature>
        </config-file>
 
        <source-file src="src/android/DialogGPS.java" target-dir="src/cl/rmd/cordova/dialoggps" />
        <source-file src="www/icon/drawable-hdpi/ic_location.png"  target-dir="app/src/main/res/drawable-hdpi/"/> <!--  target paths updated -->
        <source-file src="www/icon/drawable-mdpi/ic_location.png"  target-dir="app/src/main/res/drawable-mdpi/"/>
        <source-file src="www/icon/drawable-xhdpi/ic_location.png"  target-dir="app/src/main/res/drawable-xhdpi/"/>
        <source-file src="www/icon/drawable-xxhdpi/ic_location.png"  target-dir="app/src/main/res/drawable-xxhdpi/"/>
        <source-file src="www/icon/drawable-xxxhdpi/ic_location.png"  target-dir="app/src/main/res/drawable-xxxhdpi/"/>

        <config-file target="AndroidManifest.xml"    parent="/manifest">
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
        </config-file>
```

I think the offending line is: 
`<source-file src="src/android/DialogGPS.java" target-dir="src/cl/rmd/cordova/dialoggps" />`

Just not certain where the target-dir should be.  It put the DialogGPS.java file in `app/src/main/java/cl/rmd/cordova/dialoggps/`

**Comment by dpa99c** [comment] 2018-08-22 14:28
Looking at how I'm specifying Android files [in the Diagnostic plugin](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L258), you need to use relative paths which enables Cordova to prepend the relevant filepath prefix. That allows the plugin to work with both `cordova-android@6` and `cordova-android@7`.

So try something like:

    <platform name="android">
        <config-file target="config.xml" parent="/*">  
            <feature name="DialogGPS">
                <param name="android-package" value="cl.rmd.cordova.dialoggps.DialogGPS"/>
            </feature>
        </config-file>
 
        <source-file src="src/android/DialogGPS.java" target-dir="src/cl/rmd/cordova/dialoggps" />
        <resource-file src="www/icon/drawable-hdpi/ic_location.png"  target-dir="res/drawable-hdpi/"/> 
        <resource-file src="www/icon/drawable-mdpi/ic_location.png"  target-dir="res/drawable-mdpi/"/>
        <resource-file src="www/icon/drawable-xhdpi/ic_location.png"  target-dir="res/drawable-xhdpi/"/>
        <resource-file src="www/icon/drawable-xxhdpi/ic_location.png"  target-dir="res/drawable-xxhdpi/"/>
        <resource-file src="www/icon/drawable-xxxhdpi/ic_location.png"  target-dir="res/drawable-xxxhdpi/"/>

        <config-file target="AndroidManifest.xml"    parent="/manifest">
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
        </config-file>

**Comment by rolinger** [comment] 2018-08-22 15:59
Ok...will try it out.  Uninstalling the plugin jacked my build so I am manually scrapping out all references to it before I can try it again.

Do you think this target-dir needs to be changed to?  The error I did get was 'class not found' which I assume meant it couldn't find the 'DialogGPS.java' file.
`<source-file src="src/android/DialogGPS.java" target-dir="src/cl/rmd/cordova/dialoggps" />`

**Comment by rolinger** [comment] 2018-08-22 18:08
Tried your method.  It installed without issue but it failed to compile...it returned the same compile errors are the original plugin:

` could not write to dest file \app\platforms\android\res\xml\config.xml`

**Comment by rolinger** [comment] 2018-08-22 18:10
My `changed to` method above installed and compiled without issue, but when running it to the device the app failed to launch with this error message on the phone:  `Alert: Error initializing Cordova: class not found` - which to me implies it has something to do with where the DialogGPS.java file is being written to.
