### ISSUE TITLE
build err

### ISSUE THREAD

**Issue by pyeonjaesik** [dpa99c/cordova-plugin-request-location-accuracy#52] opened 2018-05-18 18:49 UTC
**I'm submitting a ...**  (check one with "x"):
- [x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

**Expected behavior:**

Just build succesfully
**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- 8.0.0
- Cordova platform version
	- `Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
- Plugins & versions installed in project (including this plugin)
    - com.napolitano.cordova.plugin.intent 0.1.3 "IntentPlugin"
cordova-android-firebase-gradle-release 1.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 1.4.1 "cordova-android-play-services-gradle-release"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.6 "Diagnostic"
- Dev machine OS and version, e.g.
    - Windows 10
        
_Runtime issue_
- Device details
    galaxy A7
- OS details
    - _e.g. iOS 11.2, Android 8.1_	
	
_Android build issue:_	
- Node JS version
    - v6.11.4`
- Gradle version
	- `ls platforms/android/.gradle` - I can not know. I just get only err.

- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
          android:targetSdkVersion="26"
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - `ionic info`
- Installed Ionic Native modules and versions
    - `npm list | grep "@ionic-native"`

**Related code:**

```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**

<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment] 2018-05-18 18:50
Your problem is `cordova-plugin-fcm@2.1.2`. It [pins v3.0.0 of Google Services plugin](https://github.com/fechanique/cordova-plugin-fcm/blob/master/src/android/FCMPlugin.gradle#L8).

Until recent versions of the Google Services plugin (v3.3.0+), the Google Services plugin referenced a specific version of the Play Services library. See [Android Library Versions](https://developers.google.com/android/guides/versioning) for details.

Google Services plugin v3.0.0 references Play Services v9.0.0. If you check the [release history](https://developers.google.com/android/guides/releases#may_2016_-_version_90), v9.0.0 was released in May 2016.

You cannot override the version of Play Services specified by the Google Services plugin with  [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release). However, you can use it to align other plugins to this version:

    cordova plugin add cordova-android-play-services-gradle-release  --variable PLAY_SERVICES_VERSION=9.0.0

But since v9.0.0 is so old, you may find other plugins reference newer features of the Play Services library which are not present in v9.0.0.

However! I'm working on another new plugin - `cordova-android-google-services-plugin-gradle-release` - which will enable you to override the Google Services plugin version specified by `cordova-plugin-fcm` (or other plugins) and therefore give you back control.

This is not strictly an issue with this plugin, but more a problem with how Cordova handles Gradle dependencies on the Android platform. Ideally, the cordova-android platform should allow finer grain control of Gradle dependencies, allowing you to resolve these build problems without needing to use plugins to override dependencies other plugins.

**Comment by pyeonjaesik** [comment] 2018-05-18 18:59
I tried
cordova plugin add cordova-android-play-services-gradle-release  --variable PLAY_SERVICES_VERSION=9.0.0
But I got following err.
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.google.android.gms:play-services-stats:9.0.0.
  Searched in the following locations:
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/m2repository/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/m2repository/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.aar
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.aar
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.aar
      https://jcenter.bintray.com/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.pom
      https://jcenter.bintray.com/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.aar
      https://maven.google.com/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.pom
      https://maven.google.com/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.aar
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.pom
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-stats/9.0.0/play-services-stats-9.0.0.aar
  Required by:
      project :app > com.google.firebase:firebase-messaging:15.0.2 > com.google.firebase:firebase-iid:15.1.0
      project :app > com.google.firebase:firebase-core:15.0.2 > com.google.firebase:firebase-analytics:15.0.2
      project :app > com.google.firebase:firebase-core:15.0.2 > com.google.firebase:firebase-analytics:15.0.2 > com.google.firebase:firebase-analytics-impl:15.0.2
> Could not find com.google.android.gms:play-services-measurement-base:9.0.0.
  Searched in the following locations:
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/m2repository/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/m2repository/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.aar
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.aar
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.aar
      https://jcenter.bintray.com/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.pom
      https://jcenter.bintray.com/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.aar
      https://maven.google.com/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.pom
      https://maven.google.com/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.aar
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.pom
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-measurement-base/9.0.0/play-services-measurement-base-9.0.0.aar
  Required by:
      project :app > com.google.firebase:firebase-core:15.0.2 > com.google.firebase:firebase-analytics:15.0.2
      project :app > com.google.firebase:firebase-core:15.0.2 > com.google.firebase:firebase-measurement-connector-impl:15.0.0
      project :app > com.google.firebase:firebase-core:15.0.2 > com.google.firebase:firebase-analytics:15.0.2 > com.google.firebase:firebase-analytics-impl:15.0.2
> Could not find com.google.android.gms:play-services-ads-identifier:9.0.0.
  Searched in the following locations:
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/m2repository/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/m2repository/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.aar
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.aar
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.pom
      file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.aar
      https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.pom
      https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.aar
      https://maven.google.com/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.pom
      https://maven.google.com/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.aar
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.pom
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-identifier/9.0.0/play-services-ads-identifier-9.0.0.aar
  Required by:
      project :app > com.google.firebase:firebase-core:15.0.2 > com.google.firebase:firebase-analytics:15.0.2 > com.google.firebase:firebase-analytics-impl:15.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by dpa99c** [comment] 2018-05-18 19:05
This error is because `cordova-plugin-fcm` is [pulling in the latest version of Firebase](https://github.com/fechanique/cordova-plugin-fcm/blob/master/plugin.xml#L68) (`.+`) rather than pinning it. Firebase v15.0.2 needs requires features from a newer version of the Play Services library than v9.0.0.

As it currently stands, `cordova-plugin-fcm` is incompatible with this plugin and most other plugins that use Google libraries. I advise switching to `cordova-plugin-firebase` if possible, which provides the same FCM functionality, but is better maintained.

**Comment by pyeonjaesik** [comment] 2018-05-18 19:42
Thank you!
I tried cordova plugin rm cordova-plugin-fcm
And cordova plugin add cordova-plugin-firebase.
It works well!

**Comment by dpa99c** [comment] 2018-05-20 08:51
Closing this as the underlying problem is caused by `cordova-plugin-fcm`, not this plugin

**Closed as completed by dpa99c** 2018-05-20 08:51 UTC
